### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [ChickenFur/django-employee-list#2]
Hi @ChickenFur , thanks for the submission and including a demo and video. I spent some time using the demo and have a few requests for improvement.

- When the list page loads the first time (or after creating/editing users), it flashes an empty list with 0 members. It was a bit confusing for me, would be better to have an explicit loading state, or preserve existing data until the update is fetched.
- The same is true on the edit page, sometimes it takes a while for the data to populate so I see an empty form, leading to confusion.
- I think this is a bug scenario: 1) edit a user, clear out the phone number and hit save. The app goes back to the list but still shows the existing phone number. If the phone number is required, I would expect a validation error that keeps me on the form.
- Same when I hit "Save" on an empty form for a new user, it goes back to the list. I would expect to stay on the page and see inline errors on required fields in this situation.

Thanks,
Adam

**Comment by ChickenFur** [comment]
Thanks for the feedback.

1. Added a loading state for the team list
2. added a loading state for the edit page
3. set input fields to be required and added some minimum lengths and regex
4. fixed by the required settings for input

This commit should fix these issues: https://github.com/ChickenFur/django-employee-list/commit/75281089be59df9555fe918b43db3953b91b407a


![image](https://github.com/user-attachments/assets/60ba6325-5ea6-43e6-9c23-e678b8c54fa1)
![image](https://github.com/user-attachments/assets/f5ea08c3-d78a-4d0e-aaf2-b264d559dfab)
![image](https://github.com/user-attachments/assets/8ffda817-a6ec-484d-95fc-1019667f36b1)


Lots of other things could be done to improve this.

Library for handling api calls and loading state:
https://tanstack.com/query/latest/docs/framework/react/overview
 https://tanstack.com/query/latest/docs/framework/react/guides/background-fetching-indicators

It could use some design touch and some tests for the API and front end.

I certainly enjoyed diving into Django and creating this.

Christen
